### ISSUE TITLE
Error starting OmniSharp

### ISSUE THREAD

**Issue by dbaeumer** [OmniSharp/omnisharp-server#213]
_From @wind39 on April 20, 2016 19:53_

- VSCode Version: 1.0.0
- OS Version: Kubuntu 16.04

Steps to Reproduce:

1. Install C# extension.
2. Try to edit an existing C# project, already containing a .csproj file in the folder.

[INFO] Starting OmniSharp at '/home/william/Documents/Projects/SQL/SQL.sln'...
[INFO] Started OmniSharp from '/home/william/.vscode/extensions/ms-vscode.csharp-0.3.7/bin/omnisharp' with process id 13156...
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Framework.Runtime.Loader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
File name: 'Microsoft.Framework.Runtime.Loader, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
  at dnx.host.RuntimeBootstrapper.ExecuteAsync (System.String[] args) <0x40d53690 + 0x00857> in <filename unknown>:0 
  at dnx.host.RuntimeBootstrapper.Execute (System.String[] args) <0x40d53460 + 0x00063> in <filename unknown>:0 
[ERROR] Error: Failed to start OmniSharp

_Copied from original issue: Microsoft/vscode#5569_

**Comment by samjudson** [comment]
I am also getting a very similar error, but I'm not sure if its the same cause.

> [INFO] Starting OmniSharp at 'c:\Users\Sam\Documents\VsCode\Test1'...
> [INFO] Started OmniSharp from 'C:\Users\Sam\.vscode\extensions\ms-vscode.csharp-0.3.7\bin\omnisharp.cmd' with process id 5116...
> System.IO.FileNotFoundException: Could not load file or assembly 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.
> File name: 'Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
>    at Microsoft.Framework.Runtime.GlobalSettings.TryGetGlobalSettings(String path, GlobalSettings& globalSettings)
>    at Microsoft.Framework.Runtime.ProjectResolver.Initialize(String projectPath, String rootPath)
>    at Microsoft.Framework.Runtime.ProjectResolver..ctor(String projectPath, String rootPath)
>    at Microsoft.Framework.Runtime.ApplicationHostContext..ctor(IServiceProvider serviceProvider, String projectDirectory, String packagesDirectory, String configuration, FrameworkName targetFramework, ICache cache, ICacheContextAccessor cacheContextAccessor, INamedCacheDependencyProvider namedCacheDependencyProvider, IAssemblyLoadContextFactory loadContextFactory, Boolean skipLockFileValidation)
>    at Microsoft.Framework.Runtime.DefaultHost.Initialize(DefaultHostOptions options, IServiceProvider hostServices)
>    at Microsoft.Framework.Runtime.DefaultHost..ctor(DefaultHostOptions options, IServiceProvider hostServices)
>    at Microsoft.Framework.ApplicationHost.Program.Main(String[] args)
> 
> WRN: Assembly binding logging is turned OFF.
> To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
> Note: There is some performance penalty associated with assembly bind failure logging.
> To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
> 
> [ERROR] Error: Failed to start OmniSharp

The two INFO lines come up immediately, and the ERROR comes up about 60 seconds afterwards.

I has installed VSCode a few days ago, and the OmniSharp extension, and created a simple test project using .Net code - hello world basically. Everything went fine. 

Then yesterday I then downloaded a project of mine from Github, and tried to create a project.json file for it (no idea if this would work). Once I got a valid project.json file I started to get the above error. I then returned to the Test project and am now getting this error on that project too.

If I look in the extensions\ms-vscode.csharp-0.3.7\bin\packages directory I have Newtonsoft.Json version 7.0.1, but not 6.0.0.0 as mentioned in the error message above.

Hope this helps.

**Comment by cra0zy** [comment]
I have the exact same problem.
